export const ENV_VARS = {
  DATABASE_URL: 'DATABASE_URL',
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  RESET_PASSWORD_LINK: 'RESET_PASSWORD_LINK',
  MAIL_FROM: 'MAIL_FROM',
};

