-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "receiver_lat" SET DEFAULT 0,
ALTER COLUMN "receiver_lat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "receiver_lng" SET DEFAULT 0,
ALTER COLUMN "receiver_lng" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sender_lat" SET DEFAULT 0,
ALTER COLUMN "sender_lat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "sender_lng" SET DEFAULT 0,
ALTER COLUMN "sender_lng" SET DATA TYPE DOUBLE PRECISION;
